function edu_ucsd_ncmir_WIB_WebImageBrowser(){var P='',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Ec='../WIB.css',xc='.cache.html',_='/',lb='//',cc='10DF5918C2BD6FA1C4AC652F41107336',dc='1DD86AE91CA4A48D5043D7A4D06EA933',ec='2C8B965C192D789027DE940F71F87E27',fc='337A050AB0CEEC6054836BFED54FF71C',gc='36239894D95B322EDF1926AC868C6022',hc='601E9EC97C030C58A0819F019C235C7E',ic='6263F4ED27F58C4B877216F76DD3671D',jc='6840065F8B94DC54099C19E47B5B9689',kc='6F6DBED92A359F0B05BDE78FD3F03B1B',lc='714249C4270CD9B1B16BBAB7FE6FF4BC',mc='8F39BA268B982223A59D99C083A7EF05',wc=':',pb='::',Gc='<script defer="defer">edu_ucsd_ncmir_WIB_WebImageBrowser.onInjectionDone(\'edu.ucsd.ncmir.WIB.WebImageBrowser\')<\/script>',hb='<script id="',sb='=',$='?',nc='AFF8A7A46F0AC144921E162C2B9D4D0D',oc='BABFEEF13CA5575C7345257D2F0917D2',ub='Bad handler "',pc='D05199B2E924758FFF90E5CE38F10F60',qc='D9264F1852A15E44DD9C53D2CE448588',rc='DE402030BCA215942DD1B11B9CB1D99B',Fc='DOMContentLoaded',sc='E5ECD59C17E9557ADABD15EB96CA2D46',tc='E831B0B8798CD73DDB8B692404B571AE',uc='ECF4C6AC30B7374504127BD044F477E0',vc='FF3DBF36C7C5CBF9E3676EA5DFC40BEF',jb='SCRIPT',gb='__gwt_marker_edu.ucsd.ncmir.WIB.WebImageBrowser',Db='android',Fb='android_tablet',kb='base',cb='baseUrl',T='begin',Lb='blackberry',S='bootstrap',bb='clear.cache.gif',rb='content',Mb='desktop',Q='edu.ucsd.ncmir.WIB.WebImageBrowser',eb='edu.ucsd.ncmir.WIB.WebImageBrowser.nocache.js',ob='edu.ucsd.ncmir.WIB.WebImageBrowser::',Y='end',Yb='gecko',Zb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',yc='gwt/standard/standard.css',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',Dc='head',ac='hosted.html?edu_ucsd_ncmir_WIB_WebImageBrowser',Cc='href',Xb='ie6',Wb='ie8',Vb='ie9',yb='iframe',ab='img',Gb='ipad',Hb='ipad_retina',Ib='iphone',Jb='ipod',zb="javascript:''",zc='link',_b='loadExternalRefs',mb='meta',Cb='mgwt.os',Eb='mobile',Nb='mobile.user.agent',Ob='mobilesafari',Bb='moduleRequested',X='moduleStartup',Ub='msie',nb='name',Pb='not_mobile',Rb='opera',Ab='position:absolute;width:0;height:0;border:none',Ac='rel',Kb='retina',Tb='safari',db='script',bc='selectingPermutation',R='startup',Bc='stylesheet',fb='undefined',$b='unknown',Qb='user.agent',Sb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=P,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(Q);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return H(a)}}edu_ucsd_ncmir_WIB_WebImageBrowser=null;c.gwtOnLoad(z,Q,t,y);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function D(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=n.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;n.write(hb+b+ib);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=n.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
function k(){var a=n.location;return a.href==a.protocol+lb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==P){l=h()}if(l==P){l=i()}if(l==P){l=j()}if(l==P&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(mb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(nb),g;if(f){f=f.replace(ob,P);if(f.indexOf(pb)>=0){continue}if(f==qb){g=e.getAttribute(rb);if(g){var h,i=g.indexOf(sb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}u[f]=h}}else if(f==tb){g=e.getAttribute(rb);if(g){try{A=eval(g)}catch(a){alert(ub+g+vb)}}}else if(f==wb){g=e.getAttribute(rb);if(g){try{z=eval(g)}catch(a){alert(ub+g+xb)}}}}}}
function F(a){var b=u[a];return b==null?null:b}
function G(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=n.createElement(yb);a.src=zb;a.id=Q;a.style.cssText=Ab;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Bb});a.contentWindow.location.replace(t+L)}}
w[Cb]=function(){{var b=function(){var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Db)!=-1){if(a.indexOf(Eb)!=-1){return Db}else{return Fb}}if(a.indexOf(Gb)!=-1){if(window.devicePixelRatio>=2){return Hb}return Gb}if(a.indexOf(Ib)!=-1||a.indexOf(Jb)!=-1){if(window.devicePixelRatio>=2){return Kb}return Ib}if(a.indexOf(Lb)!=-1){return Lb}return Mb}();return b}};v[Cb]={android:0,android_tablet:1,blackberry:2,desktop:3,ipad:4,ipad_retina:5,iphone:6,retina:7};w[Nb]=function(){return /(android|iphone|ipod|ipad)/i.test(window.navigator.userAgent)?Ob:Pb};v[Nb]={mobilesafari:0,not_mobile:1};w[Qb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Rb)!=-1}())return Rb;if(function(){return b.indexOf(Sb)!=-1}())return Tb;if(function(){return b.indexOf(Ub)!=-1&&n.documentMode>=9}())return Vb;if(function(){return b.indexOf(Ub)!=-1&&n.documentMode>=8}())return Wb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Xb;if(function(){return b.indexOf(Yb)!=-1}())return Zb;return $b};v[Qb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};edu_ucsd_ncmir_WIB_WebImageBrowser.onScriptLoad=function(){if(I){r=true;C()}};edu_ucsd_ncmir_WIB_WebImageBrowser.onInjectionDone=function(){q=true;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:_b,millis:(new Date).getTime(),type:Y});C()};E();D();var K;var L;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(Q))){m.location.reload();return}L=ac;K=P}o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:bc});if(!B()){try{G([Mb,Pb,Zb],cc);G([Fb,Ob,Tb],dc);G([Ib,Pb,Tb],ec);G([Gb,Pb,Tb],fc);G([Hb,Ob,Tb],gc);G([Mb,Pb,Tb],hc);G([Hb,Pb,Tb],ic);G([Mb,Ob,Tb],jc);G([Lb,Ob,Tb],kc);G([Db,Pb,Tb],lc);G([Ib,Ob,Tb],mc);G([Mb,Pb,Vb],nc);G([Kb,Pb,Tb],oc);G([Lb,Pb,Tb],pc);G([Gb,Ob,Tb],qc);G([Fb,Pb,Tb],rc);G([Mb,Pb,Wb],sc);G([Db,Ob,Tb],tc);G([Mb,Pb,Rb],uc);G([Kb,Ob,Tb],vc);K=x[H(Cb)][H(Nb)][H(Qb)];var M=K.indexOf(wc);if(M!=-1){y=Number(K.substring(M+1));K=K.substring(0,M)}L=K+xc}catch(a){return}}var N;function O(){if(!s){s=true;if(!__gwt_stylesLoaded[yc]){var a=n.createElement(zc);__gwt_stylesLoaded[yc]=a;a.setAttribute(Ac,Bc);a.setAttribute(Cc,t+yc);n.getElementsByTagName(Dc)[0].appendChild(a)}if(!__gwt_stylesLoaded[Ec]){var a=n.createElement(zc);__gwt_stylesLoaded[Ec]=a;a.setAttribute(Ac,Bc);a.setAttribute(Cc,t+Ec);n.getElementsByTagName(Dc)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(Fc,O,false)}if(N){clearInterval(N)}}}
if(n.addEventListener){n.addEventListener(Fc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(n.readyState)){J();O()}},50);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:_b,millis:(new Date).getTime(),type:T});n.write(Gc)}
edu_ucsd_ncmir_WIB_WebImageBrowser();